# Generated by Django 4.1.2 on 2025-05-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_aboutclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuesClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='web/issues/')),
            ],
            options={
                'verbose_name': 'issues',
                'verbose_name_plural': 'issues',
                'db_table': 'web_issues',
            },
        ),
    ]
