# Generated by Django 4.1.2 on 2025-05-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_issuesclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyfemmeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='web/whyfemme/')),
            ],
            options={
                'verbose_name': 'whyfemme',
                'verbose_name_plural': 'whyfemme',
                'db_table': 'web_whyfemme',
            },
        ),
    ]
