# Generated by Django 4.1.2 on 2025-05-20 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_whyfemmeclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whyfemme_text', to='web.whyfemmeclass')),
            ],
            options={
                'verbose_name': 'text',
                'verbose_name_plural': 'text',
                'db_table': 'web_text',
            },
        ),
    ]
