# Generated by Django 5.2.1 on 2025-06-05 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('panel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('hdmi_ports', models.PositiveIntegerField(blank=True, null=True)),
                ('usb_ports', models.PositiveIntegerField(blank=True, null=True)),
                ('refresh_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('energy_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('speaker_type', models.CharField(blank=True, choices=[('Bluetooth', 'Bluetooth'), ('Wired', 'Wired')], max_length=50, null=True)),
                ('connectivity', models.CharField(blank=True, choices=[('Bluetooth', 'Bluetooth'), ('AUX', 'AUX'), ('USB', 'USB'), ('Wi-Fi', 'Wi-Fi')], max_length=50, null=True)),
                ('power_source', models.CharField(blank=True, choices=[('Battery', 'Battery'), ('Wired', 'Wired')], max_length=50, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Capacity in cubic feet', max_digits=5, null=True)),
            ],
            options={
                'db_table': 'product_types',
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ac_release_date',
            new_name='release_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ac_capacity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ac_energy_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ac_features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ac_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ac_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='connectivity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='door_style',
        ),
        migrations.RemoveField(
            model_name='product',
            name='frequency_range',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_ice_maker',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_water_dispenser',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hdmi_ports',
        ),
        migrations.RemoveField(
            model_name='product',
            name='noise_level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='product',
            name='panel_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='power_source',
        ),
        migrations.RemoveField(
            model_name='product',
            name='refresh_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='refrigerator_energy_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='refrigerator_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='product',
            name='screen_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='smart_tv',
        ),
        migrations.RemoveField(
            model_name='product',
            name='speaker_features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='speaker_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='speaker_release_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='speaker_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tv_energy_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='usb_ports',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='product',
            name='dynamic_properties',
            field=models.JSONField(blank=True, help_text="Store custom fields for each product type. For example, a TV may have keys like 'screen_size', 'resolution', etc., while a Speaker might have 'speaker_type' or 'connectivity'.", null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_type'),
        ),
    ]
